about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Themefisher"
contact_form_action = "#"
copyright = "@Copyright babytomother.org - 2022"
custom_script = ""
description = "This is meta description"
email = "info@email.com"
favicon = "/exampleSite/assets/images/logotrans.png"
featured_post_title = "Featured Post"
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
image = "/exampleSite/assets/images/logotrans.png"
logo = "/exampleSite/assets/images/logotrans.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = "+211234565523"
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "exampleSite/static/images/banner-bg-shape.svg"
button_label = "Explore"
button_link = "about/"
content = "BabytoMother guide women for a personal development, education, healthcare and child care"
enable = true
image = "exampleSite/static/images/banner-nobg.png"
title_large = "Welcome **!**"
title_small = "to BabytoMother"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = true
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
